name: Security-First CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '18'

jobs:
  security-audit:
    name: Security Audit & SAST
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run ESLint Security Rules
      run: npm run lint
      
    - name: Run NPM Security Audit
      run: npm audit --audit-level moderate
      
    - name: Static Application Security Testing (SAST)
      uses: github/super-linter@v4
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_TYPESCRIPT_ES: true
        VALIDATE_JAVASCRIPT_ES: true
        
    - name: Secret Scanning
      run: |
        # Check for potential secrets in code
        if grep -r "sk_" --include="*.ts" --include="*.js" src/; then
          echo "❌ Potential Stripe secret key found in source code!"
          exit 1
        fi
        if grep -r "firebase_private_key" --include="*.ts" --include="*.js" src/; then
          echo "❌ Potential Firebase private key found in source code!"
          exit 1
        fi
        echo "✅ No obvious secrets found in source code"

  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    needs: security-audit
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build TypeScript
      run: npm run build
      
    - name: Run Tests
      run: npm test