name: Security-First CI/CD Pipeline
# Updated: 2025-07-25 - Fixed ESLint v9 compatibility

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '18'

jobs:
  security-audit:
    name: Security Audit & SAST
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run ESLint Security Rules
      run: npm run lint
      
    - name: Run NPM Security Audit
      run: npm audit --audit-level moderate
      
    - name: Static Application Security Testing (SAST)
      uses: github/super-linter@v6
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_TYPESCRIPT_ES: true
        VALIDATE_JAVASCRIPT_ES: true
        FILTER_REGEX_EXCLUDE: ".*/(build_config_analysis\.js|firebase-config-simulation\.js|landing-page-migration-simulation\.js|firebase-setup/public/assets/.*\.js)$"
        
    - name: Secret Scanning
      run: |
        # Check for potential secrets in code (excluding test regex patterns)
        if grep -r "sk_" --include="*.ts" --include="*.js" src/ | grep -v "/.*sk_.*/" | grep -v "toMatch.*sk_" | grep -q .; then
          echo "❌ Potential Stripe secret key found in source code!"
          exit 1
        fi
        if grep -r "firebase_private_key" --include="*.ts" --include="*.js" src/; then
          echo "❌ Potential Firebase private key found in source code!"
          exit 1
        fi
        echo "✅ No obvious secrets found in source code"

  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    needs: security-audit
    
    env:
      FIREBASE_API_KEY: "test_api_key_for_ci_cd"
      FIREBASE_AUTH_DOMAIN: "test-project.firebaseapp.com"
      FIREBASE_PROJECT_ID: "test-project-id"
      FIREBASE_STORAGE_BUCKET: "test-project.appspot.com"
      FIREBASE_MESSAGING_SENDER_ID: "1234567890"
      FIREBASE_APP_ID: "1:1234567890:web:abcdef123456"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build TypeScript
      run: npm run build
      
    - name: Run Tests
      run: npm test